//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.WPF.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.WPF.Common.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex — Open.
        /// </summary>
        internal static string Actions_ForexOpen {
            get {
                return ResourceManager.GetString("Actions_ForexOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures — Pre-market.
        /// </summary>
        internal static string Actions_FuturesPremarket {
            get {
                return ResourceManager.GetString("Actions_FuturesPremarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKET STATUS.
        /// </summary>
        internal static string Actions_MarketStatus {
            get {
                return ResourceManager.GetString("Actions_MarketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK ACTIONS.
        /// </summary>
        internal static string Actions_QuickActions {
            get {
                return ResourceManager.GetString("Actions_QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Trade Tracking System.
        /// </summary>
        internal static string App_Subtitle {
            get {
                return ResourceManager.GetString("App_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Journal.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.0.
        /// </summary>
        internal static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        internal static string Dashboard_ImportCsv {
            get {
                return ResourceManager.GetString("Dashboard_ImportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + New Trade.
        /// </summary>
        internal static string Dashboard_NewTrade {
            get {
                return ResourceManager.GetString("Dashboard_NewTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Dashboard_Refresh {
            get {
                return ResourceManager.GetString("Dashboard_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Dialog.
        /// </summary>
        internal static string Dashboard_SampleDialog {
            get {
                return ResourceManager.GetString("Dashboard_SampleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Trading Journal.
        /// </summary>
        internal static string Dashboard_Welcome {
            get {
                return ResourceManager.GetString("Dashboard_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline architecture is ready..
        /// </summary>
        internal static string Dialog_SampleMessage {
            get {
                return ResourceManager.GetString("Dialog_SampleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Journal.
        /// </summary>
        internal static string Dialog_SampleTitle {
            get {
                return ResourceManager.GetString("Dialog_SampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        internal static string Kpi_AllTime {
            get {
                return ResourceManager.GetString("Kpi_AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG R:R.
        /// </summary>
        internal static string Kpi_AvgRR {
            get {
                return ResourceManager.GetString("Kpi_AvgRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        internal static string Kpi_Last30Days {
            get {
                return ResourceManager.GetString("Kpi_Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NET P&amp;L.
        /// </summary>
        internal static string Kpi_NetPnl {
            get {
                return ResourceManager.GetString("Kpi_NetPnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk / Reward.
        /// </summary>
        internal static string Kpi_RiskReward {
            get {
                return ResourceManager.GetString("Kpi_RiskReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string Kpi_ThisMonth {
            get {
                return ResourceManager.GetString("Kpi_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL TRADES.
        /// </summary>
        internal static string Kpi_TotalTrades {
            get {
                return ResourceManager.GetString("Kpi_TotalTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN RATE.
        /// </summary>
        internal static string Kpi_WinRate {
            get {
                return ResourceManager.GetString("Kpi_WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (US).
        /// </summary>
        internal static string Lang_EnUS {
            get {
                return ResourceManager.GetString("Lang_EnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español (Colombia).
        /// </summary>
        internal static string Lang_EsCO {
            get {
                return ResourceManager.GetString("Lang_EsCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Nav_Analytics {
            get {
                return ResourceManager.GetString("Nav_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string Nav_Journal {
            get {
                return ResourceManager.GetString("Nav_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Nav_Language {
            get {
                return ResourceManager.GetString("Nav_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        internal static string Nav_Live {
            get {
                return ResourceManager.GetString("Nav_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration....
        /// </summary>
        internal static string Splash_InitConfig {
            get {
                return ResourceManager.GetString("Splash_InitConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing services....
        /// </summary>
        internal static string Splash_InitServices {
            get {
                return ResourceManager.GetString("Splash_InitServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing workspace....
        /// </summary>
        internal static string Splash_InitWorkspace {
            get {
                return ResourceManager.GetString("Splash_InitWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your workspace....
        /// </summary>
        internal static string Splash_Loading {
            get {
                return ResourceManager.GetString("Splash_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string Splash_Ready {
            get {
                return ResourceManager.GetString("Splash_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready — Market data connected.
        /// </summary>
        internal static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trades recorded yet.
        /// </summary>
        internal static string Trades_Empty {
            get {
                return ResourceManager.GetString("Trades_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first trade to start tracking.
        /// </summary>
        internal static string Trades_EmptyHint {
            get {
                return ResourceManager.GetString("Trades_EmptyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;L.
        /// </summary>
        internal static string Trades_Pnl {
            get {
                return ResourceManager.GetString("Trades_Pnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT TRADES.
        /// </summary>
        internal static string Trades_RecentTrades {
            get {
                return ResourceManager.GetString("Trades_RecentTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT.
        /// </summary>
        internal static string Trades_Result {
            get {
                return ResourceManager.GetString("Trades_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIDE.
        /// </summary>
        internal static string Trades_Side {
            get {
                return ResourceManager.GetString("Trades_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYMBOL.
        /// </summary>
        internal static string Trades_Symbol {
            get {
                return ResourceManager.GetString("Trades_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all →.
        /// </summary>
        internal static string Trades_ViewAll {
            get {
                return ResourceManager.GetString("Trades_ViewAll", resourceCulture);
            }
        }
    }
}
